Traceback (most recent call last):
  File "/Users/jaehyeong/workspace/worker_env/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/Users/jaehyeong/workspace/worker_env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jaehyeong/workspace/worker_env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jaehyeong/workspace/worker_env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jaehyeong/workspace/worker_env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jaehyeong/workspace/worker_env/lib/python3.7/site-packages/uvicorn/main.py", line 435, in main
    run(app, **kwargs)
  File "/Users/jaehyeong/workspace/worker_env/lib/python3.7/site-packages/uvicorn/main.py", line 461, in run
    server.run()
  File "/Users/jaehyeong/workspace/worker_env/lib/python3.7/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Users/jaehyeong/workspace/worker_env/lib/python3.7/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/Users/jaehyeong/workspace/worker_env/lib/python3.7/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/jaehyeong/workspace/worker_env/lib/python3.7/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/Users/jaehyeong/workspace/worker_env/lib/python3.7/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 8, in <module>
    import pdftotext
ImportError: dlopen(/Users/jaehyeong/workspace/worker_env/lib/python3.7/site-packages/pdftotext.cpython-37m-darwin.so, 0x0002): symbol not found in flat namespace '__ZN7poppler24set_debug_error_functionEPFvRKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPvES9_'
